name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # Make sure you're really using .NET 9, or change to 8.0.x or 7.0.x if needed

    - name: Restore dependencies
      run: dotnet restore ./CyberChatBotGUIFinal/CyberChatBotGUIFinal.csproj

    - name: Build
      run: dotnet build ./CyberChatBotGUIFinal/CyberChatBotGUIFinal.csproj --no-restore --configuration Release

    - name: Run Tests
      run: echo "No tests implemented"

