name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Update if you used a different version

    - name: Restore dependencies
      run: dotnet restore ./CyberChatBotFinalGUI/CyberChatBotFinalGUI.csproj

    - name: Build
      run: dotnet build ./CyberChatBotFinalGUI/CyberChatBotFinalGUI.csproj --no-restore --configuration Release

    - name: Run Tests
      run: echo "No tests implemented"
